baseURL = 'https://blog.keith.collister.xyz/'
languageCode = 'en-gb'
theme = 'hello-friend'
title = "keith's blog"
paginate = 10

enableEmoji = true
enableRobotsTXT = true

[params]
  contentTypeName = 'posts'
  defaultTheme = 'dark'
  showReadingTime = true

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "keith's blog"
      logoHomeLink = '/'